//This is a copy of an API Json
//NOTE: THIS COPY "API" CAN BE ACCESIBLE FOR ANYONE IN THE TEAM (TESTING PURPOSES)
export default function handler(req, res) {
  res.status(200).json({
    status: "success",
    totalResults: 41295,
    results: [
      {
        article_id: "c46d5fc50d86a23448a32f6a0b0ed8d1",
        title:
          "BPSC TRE 3.0 registration window closes today; apply now at bpsc.bih.nic.in",
        link: "https://scroll.in/announcements/1064272/bpsc-tre-3-0-registration-window-closes-today-apply-now-at-bpsc-bih-nic-in?utm_source=rss&utm_medium=public",
        keywords: null,
        creator: ["Scroll Staff"],
        video_url: null,
        description:
          "Eligible candidates can apply for the vacancies on the Commission’s official website bpsc.bih.nic.in till today without a late fee.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:15:00",
        image_url:
          "https://sc0.blr1.cdn.digitaloceanspaces.com/article/160339-zzenkkjsvk-1623673392.jpg",
        source_id: "scroll",
        source_url: "https://scroll.in",
        source_icon: "https://i.bytvi.com/domain_icons/scroll.png",
        source_priority: 26952,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "33031c5a54e420d42ed951a9bf527044",
        title: "Thai King highly values Vietnam-Thailand friendship",
        link: "https://en.vietnamplus.vn/thai-king-highly-values-vietnamthailand-friendship/280001.vnp",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:15:00",
        image_url: null,
        source_id: "vietnamplus",
        source_url: "https://www.vietnamplus.vn",
        source_icon: null,
        source_priority: 248784,
        country: ["vietnam"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "5e5bf1ea3c5b012b15020d252749225e",
        title: "Malta News Briefing – Monday 26 February 2024",
        link: "https://cde.news/malta-news-briefing-monday-26-february-2024/",
        keywords: ["malta24"],
        creator: ["Cde"],
        video_url: null,
        description:
          "Morning Briefing e-money firm at centre of major investigation – reportAn e-money company located in Gżira has become a focal point in an international investigation into an alleged “Russian-Eurasian criminal network,” according to information uncovered revealed on The Times of Malta. This week, police conducted searches at Papaya, the financial institution suspected of providing ‘money-laundering […]",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:15:00",
        image_url:
          "https://i0.wp.com/cde.news/wp-content/uploads/2023/06/pexels-photo-8909170.jpeg?resize=1300%2C540&ssl=1",
        source_id: "cde_news",
        source_url: "https://cde.news/malta-24-news-briefing",
        source_icon: "https://i.bytvi.com/domain_icons/cde_news.png",
        source_priority: 1996196,
        country: ["malta"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "6097ea0aef2c9c258f97e13ebf603eca",
        title:
          "Delhi Excise Policy Case: CM Arvind Kejriwal Skips ED Summons For 7th Time",
        link: "https://news.abplive.com/delhi-ncr/delhi-excise-policy-case-cm-arvind-kejriwal-skips-ed-summons-for-7th-time-1667447",
        keywords: ["delhi ncr"],
        creator: [""],
        video_url: null,
        description:
          "Delhi Excise Policy Case: CM Arvind Kejriwal Skips ED Summons For 7th Time",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:14:59",
        image_url:
          "https://feeds.abplive.com/onecms/images/uploaded-images/2024/02/26/0ac190fece6b1c7de5066a8aef78a0e21708920881813177_original.jpg",
        source_id: "abplive",
        source_url: "http://abplive.com",
        source_icon: null,
        source_priority: 10959,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "a803bdbb4d5b8389a2e262acdbfaae60",
        title:
          "Bye-bye BSP: MP joins BJP, 3 more in talks; another 2 set for Cong, 1 for RLD",
        link: "https://timesofindia.indiatimes.com/city/lucknow/bsp-mp-joins-bjp-3-more-in-talks-2-set-for-cong-1-for-rld/articleshow/107997623.cms",
        keywords: null,
        creator: ["Pankaj Shah"],
        video_url: null,
        description:
          "BSP's MP Ritesh Pandey joined BJP, signaling a possible switchover of three more MPs from BSP to BJP. Mayawati's leadership, Lok Sabha elections, and the influence of other political parties are significant factors in these developments. BJP is finalizing its list of candidates for the upcoming LS polls.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:14:53",
        image_url:
          "https://static.toiimg.com/photo/msid-107997791,imgsize-24302.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "ca0e732f13d14986d5577efed7343643",
        title: "Cartoon: February 26, 2024",
        link: "https://www.the-star.co.ke/cartoon/2024-02-26-cartoon-february-26-2024/",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:14:48",
        image_url: null,
        source_id: "thestarke",
        source_url: "https://www.the-star.co.ke",
        source_icon: "https://i.bytvi.com/domain_icons/thestarke.png",
        source_priority: 38358,
        country: ["kenya"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "c4ced06388cf217c07dcb53963392d99",
        title:
          "President Hakainde Hichilema Attended Burial of Late Namibian President Dr. Hage Gottfried Geingob",
        link: "https://www.lusakatimes.com/2024/02/26/president-hakainde-hichilema-attended-burial-of-late-namibian-president-dr-hage-gottfried-geingob/",
        keywords: ["general news"],
        creator: ["Chief Editor"],
        video_url: null,
        description:
          "Amidst solemn reverence, dignitaries and mourners gathered at Heroes Square in Windhoek to bid farewell to the late former President of Namibia, His Excellency Dr. Hage Gottfried Geingob. The ceremony, attended by leaders and citizens alike, honored the legacy and contributions of the courageous son of Africa. In a heartfelt message, President Hakainde Hichilema […]",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:14:42",
        image_url: null,
        source_id: "lusakatimes",
        source_url: "https://www.lusakatimes.com",
        source_icon: "https://i.bytvi.com/domain_icons/lusakatimes.png",
        source_priority: 220218,
        country: ["zambia"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "6eb03e029dd2d96010190773a777940b",
        title:
          "Ludhiana zoo gets ready to welcome a pair of leopards, tiger into its fold",
        link: "https://timesofindia.indiatimes.com/city/ludhiana/ludhiana-zoo-to-welcome-a-pair-of-leopards-and-a-tiger/articleshow/107997616.cms",
        keywords: null,
        creator: ["Payal Dhawan"],
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:14:38",
        image_url:
          "https://static.toiimg.com/photo/msid-107997615,imgsize-165642.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "4f116db5ff15c7cf87625a2de90760ab",
        title: "Cawnpore Sunday league match held",
        link: "https://timesofindia.indiatimes.com/city/kanpur/cawnpore-sunday-league-match-panther-xi-defeats-renu-broadband-by-9-wickets/articleshow/107997614.cms",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:14:36",
        image_url:
          "https://static.toiimg.com/photo/msid-107997614,imgsize-.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "519c6ce5773507af8536fcdc79605b34",
        title: "WATCH: Protesters clash with police in Israel",
        link: "https://www.skynews.com.au/world-news/watch-protesters-clash-with-police-in-israel/video/dc35cad05b5ca6e6dc629250c0f070ba",
        keywords: [
          "global affairs",
          "world",
          "fb",
          "global",
          "msn",
          "world",
          "yt",
        ],
        creator: [""],
        video_url: null,
        description:
          "Footage has emerged of chaotic and violent scenes in Tel Aviv of anti-government demonstrators clashing with police. Israel Police shared vision of officers using water cannons against some groups of protesters. Demonstrators at a nearby rally called for the return of hostages being held in Gaza. Israel’s government is evaluating a potential ceasefire deal in its war with Hamas. A multinational committee is in Paris to negotiate a deal for the release of hostages.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-26 04:14:33",
        image_url:
          "https://content.api.news/v3/images/bin/c0c960e67e38782ba795fe03dd7eeedd",
        source_id: "skynewsau",
        source_url: "https://www.skynews.com.au",
        source_icon: "https://i.bytvi.com/domain_icons/skynewsau.png",
        source_priority: 13361,
        country: ["australia"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
    ],
    nextPage: "1708920873321502404",
  });
}
