//This is a copy of an API Json
//NOTE: THIS COPY "API" CAN BE ACCESIBLE FOR ANYONE IN THE TEAM (TESTING PURPOSES)
export default function handler(req, res) {
  res.status(200).json({
    status: "success",
    totalResults: 333107,
    results: [
      {
        article_id: "a55a68ebe378779d85374ae9a3a7aa35",
        title: "Polisi Ringkus Sindikat Penjual Bayi di Tambora Jakarta Barat",
        link: "https://metro.sindonews.com/read/1325667/170/polisi-ringkus-sindikat-penjual-bayi-di-tambora-jakarta-barat-1708484544",
        keywords: ["metro", "peristiwa"],
        creator: null,
        video_url: null,
        description:
          "Polsek Tambora, Polres Metro Jakarta Barat mengamankan tiga tersangka anggota sindikat jual beli bayi. Kasus ini terbongkar setelah pengembangan kasus laporan bayi hilang di Tambora.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://pict.sindonews.net/dyn/850/pena/news/2024/02/21/170/1325667/polisi-ringkus-sindikat-penjual-bayi-di-tambora-jakarta-barat-xze.jpg",
        source_id: "sindonews",
        source_url: "https://www.sindonews.com",
        source_icon: null,
        source_priority: 329339,
        country: ["indonesia"],
        category: ["top"],
        language: "indonesian",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "7d9688f9735d61747c38bfc8dec1f067",
        title: "Status representasi Inspektor Sheila 20 Mac",
        link: "https://www.sinarharian.com.my/article/650616/berita/semasa/status-representasi-inspektor-sheila-20-mac",
        keywords: null,
        creator: ["NOOR AZLIDA ALIMIN"],
        video_url: null,
        description:
          "KUALA LUMPUR - Status representasi pegawai polis kontroversi, Inspektor Sheila untuk membatalkan pertuduhan menyebabkan kegusaran orang awam dengan membunyikan hon kereta dalam tempoh lama ditetapkan pada 20 Mac depan di Mahkamah Majistret di sini. Peguam, M Manoharan yang mewakili inspektor itu atau nama sebenarnya Sheila Sharon Steven Kumar, 36, mengesahkan perkara itu, ketika ditemui di luar mahkamah pada Rabu, selepas sebutan kes berkenaan di hadapan Majistret, Illi Marisqa Khalizan. Menurutnya, representasi difailkan kepada Jabatan Peguam Negara (AGC) pada Selasa, dengan alasan tuduhan terhadap anak guamnya itu remeh. Selain alasan berkenaan, beliau berkata, representasi setebal 20 muka surat itu menyatakan bahawa anak guamnya merupakan mangsa dalam kes yang tular berkenaan. “Ketika sebutan kes, mahkamah menetapkan prosiding seterusnya pada Mac depan untuk mengetahui keputusan representasi. “Pihak pendakwaan memberitahu, mereka memerlukan masa tiga minggu untuk mengkaji dokumen yang difailkan kali pertama,” katanya. Pada 8 November tahun lalu, wanita itu didakwa melakukan mudarat awam dengan memarahi, membunyikan hon kereta dengan panjang atau lama serta menjerit di tempat kejadian sehingga mendatangkan kegusaran am terhadap seorang wanita berusia 28 tahun. Kesalahan didakwa dilakukan di tempat letak kereta, sebuah pusat beli-belah di Brickfields di sini, pada jam 5.26 petang, 16 Jun tahun lalu. Pertuduhan dibuat mengikut Seksyen 268 Kanun Keseksaan dan boleh dihukum bawah Seksyen 290 kanun sama, yang membawa hukuman denda sehingga RM400, jika sabit kesalahan.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://www.sinarharian.com.my/uploads/images/2024/02/21/2545387.jpg",
        source_id: "sinarharian",
        source_url: "https://www.sinarharian.com.my",
        source_icon: "https://i.bytvi.com/domain_icons/sinarharian.png",
        source_priority: 1110105,
        country: ["malaysia"],
        category: ["top"],
        language: "malay",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "672ed199ef67709b99ce679dcc4e100c",
        title: "Svårt få läkare stanna – andra betalar mer",
        link: "https://www.na.se/2024-02-21/svart-fa-lakare-att-stanna-i-psykiatrin-nar-andra-betalar-battre",
        keywords: null,
        creator: null,
        video_url: null,
        description: "Lista: Så mycket tjänar läkare inom psykiatrin i Örebro",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://static.bonniernews.se/bildix/api/images/7901d5af-bd6b-4635-890f-c0eb11dc666b.jpeg",
        source_id: "na_se",
        source_url: "https://www.na.se",
        source_icon: "https://i.bytvi.com/domain_icons/na_se.png",
        source_priority: 10578616,
        country: ["sweden"],
        category: ["top"],
        language: "swedish",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "a85e4c04a08c2f79015f1ab14e4e1770",
        title:
          "Alleged Kansas City Chiefs parade shooter Lyndell Mays told cops he was 'just being stupid': court docs - New York Post",
        link: "https://news.google.com/rss/articles/CBMiiwFodHRwczovL255cG9zdC5jb20vMjAyNC8wMi8yMC91cy1uZXdzL2FsbGVnZWQta2Fuc2FzLWNpdHktY2hpZWZzLXBhcmFkZS1zaG9vdGVyLWx5bmRlbGwtbWF5cy10b2xkLWNvcHMtaGUtd2FzLWp1c3QtYmVpbmctc3R1cGlkLWNvdXJ0LWRvY3Mv0gGPAWh0dHBzOi8vbnlwb3N0LmNvbS8yMDI0LzAyLzIwL3VzLW5ld3MvYWxsZWdlZC1rYW5zYXMtY2l0eS1jaGllZnMtcGFyYWRlLXNob290ZXItbHluZGVsbC1tYXlzLXRvbGQtY29wcy1oZS13YXMtanVzdC1iZWluZy1zdHVwaWQtY291cnQtZG9jcy9hbXAv?oc=5",
        keywords: null,
        creator: null,
        video_url: null,
        description:
          "Alleged Kansas City Chiefs parade shooter Lyndell Mays told cops he was 'just being stupid': court docs New York Post Couple married at Chiefs parade does their best to remember wedding day fondly amid tragedy KSHB 41 Kansas City News2 adults charged with murder of Lisa Lopez-Galvan at Chiefs parade: 'We are not done yet' KCURHow Kansas, Missouri lawmakers are responding to Kansas City shooting The Topeka Capital-JournalLyndell Mays' alleged motives for opening fire on crowd after Chiefs parade shooting Marca English",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url: null,
        source_id: "google",
        source_url: "https://news.google.com",
        source_icon: null,
        source_priority: 14,
        country: ["united states of america"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "7e62c858f3b07456a8b649a694f7394b",
        title:
          "La Liga tiếp tục giới hạn lương cho Barca, nguy cơ khủng hoảng hiện rõ",
        link: "https://thethaovanhoa.vn/la-liga-tiep-tuc-gioi-han-luong-cho-barca-nguy-co-khung-hoang-hien-ro-20240221104058904.htm",
        keywords: null,
        creator: null,
        video_url: null,
        description:
          "Tình hình khủng hoảng của câu lạc bộ Barcelona có vẻ sẽ ngày càng trở nên tồi tệ hơn sau khi họ được ban tổ chức La Liga thông báo rằng cần phải cắt giảm hóa đơn tiền lương xuống 57 triệu bảng.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://thethaovanhoa.mediacdn.vn/zoom/245_163/372676912336973824/2024/2/21/barca-1-17084868174431119245061-0-0-348-620-crop-17084868188932052323357.jpg",
        source_id: "thethaovanhoa",
        source_url: "https://thethaovanhoa.vn",
        source_icon: null,
        source_priority: 435464,
        country: ["vietnam"],
        category: ["world"],
        language: "vietnamese",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "ef2a06a93178c4b6227a67c1d1b927b5",
        title: "عید امسال بدون این برگه مهم، از خانه خارج نشوید!",
        link: "https://www.hamshahrionline.ir/news/833943/%D8%B9%DB%8C%D8%AF-%D8%A7%D9%85%D8%B3%D8%A7%D9%84-%D8%A8%D8%AF%D9%88%D9%86-%D8%A7%DB%8C%D9%86-%D8%A8%D8%B1%DA%AF%D9%87-%D9%85%D9%87%D9%85-%D8%A7%D8%B2-%D8%AE%D8%A7%D9%86%D9%87-%D8%AE%D8%A7%D8%B1%D8%AC-%D9%86%D8%B4%D9%88%DB%8C%D8%AF",
        keywords: ["اخبار اجتماعی > پليس"],
        creator: null,
        video_url: null,
        description:
          "چیزی تا تعطیلات عید نوروز نمانده و این چند روز تعطیلی هم جان می‌دهد برای یک سفر درست و حسابی. خیلی‌ها از یک‌ماه پیش بلیت هواپیما، قطار و اتوبوس‌شان را رزرو کرده‌اند و خیلی‌ها هم ترجیح می‌دهند با خودروی شخصی‌شان بزنند به دل جاده.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://media.hamshahrionline.ir/d/2024/02/20/4/4979211.jpg?ts=1708444422000",
        source_id: "hamshahrionline",
        source_url: "https://www.hamshahrionline.ir",
        source_icon: null,
        source_priority: 65239,
        country: ["iran"],
        category: ["top"],
        language: "persian",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "e47c2495a9cbfdaf5757c5e7227d1313",
        title:
          "Harris announces $5.8 billion for water infrastructure projects",
        link: "https://www.wcpo.com/harris-announces-5-8-billion-for-water-infrastructure-projects",
        keywords: null,
        creator: ["AP via Scripps News"],
        video_url: null,
        description:
          "New funding from the $1 trillion bipartisan infrastructure law will help pay for projects nationwide, like replacing old lead pipes.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://ewscripps.brightspotcdn.com/dims4/default/c00f0a7/2147483647/strip/true/crop/1280x720+0+0/resize/1280x720!/quality/90/?url=https%3A%2F%2Fcdn.scrippsnews.com%2Fimages%2Fvideos%2Fx%2F1708487770_9tcs88.jpg",
        source_id: "wcpo",
        source_url: "https://www.wcpo.com",
        source_icon: "https://i.bytvi.com/domain_icons/wcpo.png",
        source_priority: 6937,
        country: ["united states of america"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "14fd9ea6f21288a827f2a17051ec4762",
        title: "Dịch vụ lái xe hộ cho người say làm ăn ra sao trong mùa Tết?",
        link: "https://nld.com.vn/dich-vu-lai-xe-ho-cho-nguoi-say-lam-an-ra-sao-trong-mua-tet-196240221100122247.htm",
        keywords: null,
        creator: null,
        video_url: null,
        description:
          "(NLĐO)- Dịp Tết vừa qua, việc cơ quan chức năng tăng cường kiểm tra nồng độ cồn, dẫn đến nhu cầu thuê người lái xe hộ tăng mạnh",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://nld.mediacdn.vn/zoom/600_315/291774122806476800/2024/2/21/5fcd9a01512c1191807110-17084843677341274179149-1-111-453-834-crop-17084843751351901296290.jpg",
        source_id: "nld",
        source_url: "https://nld.com.vn",
        source_icon: "https://i.bytvi.com/domain_icons/nld.png",
        source_priority: 75571,
        country: ["vietnam"],
        category: ["top"],
        language: "vietnamese",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "45724f4db94cc6cf766de69f84ba7fe9",
        title:
          "Harris announces $5.8 billion for water infrastructure projects",
        link: "https://www.tmj4.com/harris-announces-5-8-billion-for-water-infrastructure-projects",
        keywords: null,
        creator: ["AP via Scripps News"],
        video_url: null,
        description:
          "New funding from the $1 trillion bipartisan infrastructure law will help pay for projects nationwide, like replacing old lead pipes.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://ewscripps.brightspotcdn.com/dims4/default/48f9290/2147483647/strip/true/crop/1280x672+0+24/resize/1200x630!/quality/90/?url=https%3A%2F%2Fcdn.scrippsnews.com%2Fimages%2Fvideos%2Fx%2F1708487770_9tcs88.jpg",
        source_id: "tmj4",
        source_url: "https://www.tmj4.com",
        source_icon: "https://i.bytvi.com/domain_icons/tmj4.png",
        source_priority: 7805,
        country: ["united states of america"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "e92ab8bca76e98845dc198042ab88c9e",
        title:
          "Stok Hingga Idul Fitri Aman, Heru Budi Kirim Ribuan Ton Beras ke Retail Modern",
        link: "https://rmol.id/politik/read/2024/02/21/610261/stok-hingga-idul-fitri-aman-heru-budi-kirim-ribuan-ton-beras-ke-retail-modern",
        keywords: ["politik"],
        creator: null,
        video_url: null,
        description:
          "Masyarakat diminta tidak khawatir terhadap ketersediaan beras di Jakarta. Meski begitu tetap diimbau agar membeli dengan bijak.Pernyataan itu disampaikan Penjabat Gubernur DKI Jakarta, Heru Budi Hartono, saat melepas pengiriman beras ke retail modern, di Komplek Pasar Induk Beras Cipinang, Pulo Gadung, Jakarta Timur, Rabu (21/2).Hari ini kita bersama stakeholder memastikan stok beras premium di Pasar Induk Cipinang terjaga ketersediaannya, tutur Heru Budi.Sehingga kita bisa mengirim 15 ribu ton.. Baca selengkapnya di https://rmol.id/politik/read/2024/02/21/610261/stok-hingga-idul-fitri-aman-heru-budi-kirim-ribuan-ton-beras-ke-retail-modern",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-21 03:57:00",
        image_url:
          "https://rmol.id/images/berita/normal/2024/02/915172_10593121022024_a-Recovered.jpg",
        source_id: "rmol",
        source_url: "https://rmol.id",
        source_icon: null,
        source_priority: 2913444,
        country: ["indonesia"],
        category: ["top"],
        language: "indonesian",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
    ],
    nextPage: "1708487820281286669",
  });
}
