//This is a copy of an API Json
//NOTE: THIS COPY "API" CAN BE ACCESIBLE FOR ANYONE IN THE TEAM (TESTING PURPOSES)
export default function handler(req, res) {
  res.status(200).json({
    status: "success",
    totalResults: 62128,
    results: [
      {
        article_id: "4cbf513f833b0b2fc01a5d39a0eb3eb1",
        title: "Province providing $302,500 to Alberta Sports Hall of Fame",
        link: "https://lethbridgenewsnow.com/2024/02/22/province-providing-302500-to-alberta-sports-hall-of-fame/",
        keywords: ["alberta"],
        creator: null,
        video_url: null,
        description:
          "The Government of Alberta is providing funding to maintain operations of the Alberta Sports Hall of Fame (ASHoF).The funding amounts to $302,500, whic...",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:59",
        image_url:
          "https://d2ksr9467jthww.cloudfront.net/20240223020256/6c7b82b8-e9a5-41cd-8b2a-45ea27c4b317.jpg",
        source_id: "lethbridgenewsnow",
        source_url: "https://lethbridgenewsnow.com",
        source_icon: null,
        source_priority: 149548,
        country: ["canada"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "133536a3c0c1cbab596bce332e807285",
        title:
          "Senior postal super recommends CBI probe into funds misappropriation",
        link: "https://timesofindia.indiatimes.com/city/ranchi/senior-postal-super-recommends-cbi-probe-into-funds-misappropriation/articleshow/107928673.cms",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:58",
        image_url:
          "https://static.toiimg.com/photo/msid-107928673,imgsize-.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "db31be958b4799b2056b11c961e75054",
        title:
          "Asian stocks rise as tech gains offset rate fears; China rebound holds",
        link: "https://www.investing.com/news/stock-market-news/asian-stocks-rise-as-tech-gains-offset-rate-fears-china-rebound-holds-3312312",
        keywords: null,
        creator: ["Investing.com"],
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:56",
        image_url: "https://i-invdn-com.investing.com/news/LYNXMPEC030H2_M.jpg",
        source_id: "investing_us",
        source_url: "https://www.investing.com",
        source_icon: null,
        source_priority: 1205,
        country: ["united states of america"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "c932c5d900f98e00d66513346876dac2",
        title: "Five things to know to start your Thursday",
        link: "https://businessday.ng/news/article/five-things-to-know-to-start-your-thursday-88/",
        keywords: ["news", "bdrecent"],
        creator: ["Kelvin Okojie"],
        video_url: null,
        description:
          "In January 2024, Nigeria’s government revenue rose to N2.07trillion, with N1.15trillion disbursed to Federal, state, and local governments. This marks read more Five things to know to start your Thursday",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:56",
        image_url:
          "https://cdn.businessday.ng/wp-content/uploads/2024/02/Cart2024FEB005-1.jpg",
        source_id: "businessday",
        source_url: "https://businessday.ng",
        source_icon: "https://i.bytvi.com/domain_icons/businessday.jpg",
        source_priority: 92206,
        country: ["nigeria"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "8e6383e8b73a835b142c67d7d7ca70ba",
        title: "NTCA team conducts security audit of tiger reserve",
        link: "https://timesofindia.indiatimes.com/city/ranchi/ntca-team-conducts-security-audit-of-tiger-reserve/articleshow/107928660.cms",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:51",
        image_url:
          "https://static.toiimg.com/photo/msid-107928660,imgsize-.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "49836251571651022080e9a9c1e10fb9",
        title: "I think it’s maybe, maybe not: Ben on availability as bowler",
        link: "https://timesofindia.indiatimes.com/city/ranchi/ben-stokes-raises-hopes-of-bowling-in-fourth-test-against-india/articleshow/107928656.cms",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:47",
        image_url:
          "https://static.toiimg.com/photo/msid-107928654,imgsize-58976.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "7dc1cdd0187de611177ca129302bdf29",
        title: "‘Sensitivity paramount to deal with Pocso cases’",
        link: "https://timesofindia.indiatimes.com/city/ranchi/sensitivity-paramount-to-deal-with-pocso-cases/articleshow/107928645.cms",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:42",
        image_url:
          "https://static.toiimg.com/photo/msid-107928645,imgsize-.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "2515b3f4296d9985a279241d626beefb",
        title: "Gumla prepares action plan to curb sickle-cell disease",
        link: "https://timesofindia.indiatimes.com/city/ranchi/gumla-takes-action-to-curb-sickle-cell-disease/articleshow/107928632.cms",
        keywords: null,
        creator: null,
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:35",
        image_url:
          "https://static.toiimg.com/photo/msid-107928632,imgsize-.cms",
        source_id: "toi",
        source_url: "https://timesofindia.indiatimes.com",
        source_icon: null,
        source_priority: 391,
        country: ["india"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "d324cf15bfd1513fd2edeb222dac6fda",
        title:
          "Sam Waterston Exits Law & Order With a Powerful Jack McCoy Story",
        link: "https://www.tvfanatic.com/2024/02/sam-waterston-exits-law-and-order-with-a-powerful-jack-mccoy-sto/",
        keywords: ["law & order", "reviews"],
        creator: ["Jack Ori"],
        video_url: null,
        description: null,
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:34",
        image_url:
          "https://tv-fanatic-res.cloudinary.com/iu/s--uCKN9aac--/c_fill,h_315,w_851/d_tv-fanatic-placeholder-square.png,f_auto,fl_lossy,q_75/v1664504014/banner/law-and-order.jpg",
        source_id: "tvfanatic",
        source_url: "https://www.tvfanatic.com",
        source_icon: "https://i.bytvi.com/domain_icons/tvfanatic.png",
        source_priority: 5286,
        country: ["united states of america"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
      {
        article_id: "8b4b29cf65f851cf34f4d660af5ab443",
        title:
          "Greece's Public Debt Grows by Over $6.5Bln in One Year - Debt Management",
        link: "https://sputnikglobe.com/20240223/greeces-public-debt-grows-by-over-65bln-in-one-year---debt-management-1116931038.html",
        keywords: null,
        creator: null,
        video_url: null,
        description:
          "ATHENS (Sputnik) - Greece's public debt, including domestic government guarantees, grew by over 6 billion euros ($6.5 billion) last year and reached 406.5 billion euros as of December 31, 2023, according to a quarterly bulletin by the country's Public Debt Management Agency (PDMA).",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2024-02-23 03:02:31",
        image_url:
          "https://cdn1.img.sputnikglobe.com/img/07e8/02/11/1116851084_0:160:3072:1888_1920x0_80_0_0_a0223f8f92f993993025db576e1b7735.jpg",
        source_id: "sputnikglobe",
        source_url: "https://sputnikglobe.com",
        source_icon: "https://i.bytvi.com/domain_icons/sputnikglobe.png",
        source_priority: 33351,
        country: ["russia"],
        category: ["top"],
        language: "english",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      },
    ],
    nextPage: "1708657351717831321",
  });
}
